name: Update Lambda Layer

on:
  push:
    paths:
      - 'aws/lambda/**'
  workflow_dispatch:

jobs:
  update-layer:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up AWS CLI and credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Install necessary dependencies (e.g., zip)
      - name: Install zip
        run: sudo apt-get install zip -y

      # Step 4: Zip the layer contents (you may need to adapt this based on your structure)
      - name: Package Lambda Layer
        run: |
          cd aws/lambda
          zip -r new_lambda_layer.zip .

      # Step 5: Update Lambda Layer
      - name: lambda_code_update
      run: |
        aws lambda update-function-code \
          --function-name ${{ vars.LAMBDA_FUNCTION_NAME }} \
          --zip-file fileb://aws/lambda/new_lambda_layer.zip